quarkus:
  http:
    cors:
      ~: true
      origins: "https://reality.havasi.me"
      methods: "GET,POST,PUT,DELETE,OPTIONS"
      headers: "*"
      expose-headers: "Content-Length,Content-Type"
      access-control-allow-credentials: true
  oidc:
    application-type: service
    provider: google
    client-id: ${GOOGLE_CLIENT_ID}
    authentication:
      user-info-required: true
  otel:
    logs:
      enabled: true
    metrics:
      enabled: true
    exporter:
      otlp:
        endpoint: "http://grafana-alloy:4317"
        protocol: "grpc"
    service:
      name: "reality-app"
    resource:
      attributes: "deployment.environment=production,service.namespace=havasi,service.instance.id=1"
  log:
    category:
      "org.mongo":
        level: "WARN"
  mongodb:
    connection-string: ${MONGODB_CONNECTION_STRING}
    database: ${MONGODB_DATABASE}
  mongock:
    migrate-at-start: true
  rest-client:
    "sreality-api":
      url: "https://www.sreality.cz"
      connect-timeout: 3000
      read-timeout: 5000
    "mailjet-api":
      url: "https://api.mailjet.com"
      connect-timeout: 3000
      read-timeout: 5000
    "idnes-api":
      url: "https://reality.idnes.cz"
      connect-timeout: 3000
      read-timeout: 10000
    "bezrealitky-api":
      url: "https://www.bezrealitky.cz"
      connect-timeout: 3000
      read-timeout: 5000
    "discord-api":
      url: "https://discord.com"
      connect-timeout: 3000
      read-timeout: 5000
  application:
    name: "reality-app"

reality:
  mailjet:
    auth:
      username: ${MAILJET_USERNAME}
      password: ${MAILJET_PASSWORD}
  scheduler:
    cron: "0 */30 6-23 * * ?"
