quarkus:
  mongodb:
    connection-string: ${MONGODB_CONNECTION_STRING}
  rest-client:
    "sreality-api":
      url: "https://www.sreality.cz"
      connect-timeout: 3000
      read-timeout: 5000
  application:
    name: "reality-app"

reality:
  scheduler:
    cron: "0 */30 6-23 * * ?"
