name: CI/CD to AWS ECR and EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build Native Docker Image and Push to ECR
    runs-on: ubuntu-latest
    outputs:
      commit_hash: ${{ steps.get_commit_hash.outputs.commit_hash }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}

      - name: Get Commit Hash
        id: get_commit_hash
        run: echo "COMMIT_HASH=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Note Commit Hash
        id: build
        run: |
          echo "::notice title=Commit Hash::${{ env.COMMIT_HASH }}"
        shell: bash

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Build Native Docker Image with Gradle
        run: |
          # Build the Quarkus native Docker image using Gradle
          ./gradlew build -Dquarkus.native.enabled=true -Dquarkus.native.container-build=true -Dquarkus.package.jar.enabled=false -Dquarkus.native.container-runtime=docker

      - name: Build, Tag, and Push Docker Image
        run: |
          # Build Docker image and tag it with commit hash
          docker build -f src/main/docker/Dockerfile.native -t reality-app:${{ env.COMMIT_HASH }} .
          docker tag reality-app:${{ env.COMMIT_HASH }} ${{ secrets.ECR_REPOSITORY }}:${{ env.COMMIT_HASH }}
          docker push ${{ secrets.ECR_REPOSITORY }}:${{ env.COMMIT_HASH }}

  deploy-to-ec2:
    name: Deploy on EC2
    needs: build-and-push
    uses: ivanhavasi/reality-app/.github/workflows/deploy-only.yaml@main
    with:
      commit_hash: ${{ needs.build-and-push.outputs.commit_hash }}
    secrets:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      MONGODB_CONNECTION_STRING: ${{ secrets.MONGODB_CONNECTION_STRING }}
